### ISSUE TITLE
MS Build error when removing $(MSBuildToolsPath)\Microsoft.CSharp.targets

### ISSUE THREAD

**Issue by kwemou** [OrleansContrib/OrleansCassandraUtils#1]
Dear all,
forked the code to upgrade to Orleans 3.1.6.
Current issue is that the code is not compiling:
Clustering\CassandraClusteringTable.cs(130,56) "OrleansQueries" does not contains a definition of 
"DeleteMembershipEntry".

I also looked in the whole repository. There is no occurence of "DeleteMembershipEntry".
Is that code somewhow generated?

Thank you and best regards
Kwemou

**Comment by kwemou** [comment]
Sorry my error:
the code compile as I added

  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />

in the

**Comment by kwemou** [comment]
Please ignore the issue.
solved

**Comment by kwemou** [comment]
Error happens when removing old targets

**Comment by RuiEusebio** [comment]
Hi, I did a fork and I put it able to work with Orleans 3.4, also I did small changes so, please take a look https://github.com/RuiEusebio/OrleansCassandraUtils

**Comment by Arshia001** [comment]
@RuiEusebio I'd ask you to create a pull request with your changes, but renaming the storage table causes backwards incompatibility.

**Comment by RuiEusebio** [comment]
I can revert the table name to storage again if you want and I will open a pull request

**Comment by Arshia001** [comment]
@RuiEusebio that'd be wonderful :)
