### ISSUE TITLE
Cannot resolve scoped service Microsoft.Extensions.Options.IOptionsSnapshot

### ISSUE THREAD

**Issue by RuiEusebio** [OrleansContrib/OrleansCassandraUtils#4]
Issue: When the application start raises this error. 

System.InvalidOperationException: Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[OrleansCassandraUtils.Persistence.CassandraGrainStorageOptions]' from root provider.

Related with: dotnet/orleans#5543

Fix: change IOptionsSnapshot to IOptionsMonitor

Pull Request: https://github.com/OrleansContrib/OrleansCassandraUtils/pull/3

**Comment by Arshia001** [comment]
Merged. Thank you!
